name: Generate Mime Types

on:
  push:
    paths:
      - "data/mime.types"
      - "data/mime.types.custom"
      - "stubs/mimeType.php.stub"

jobs:
  update:
    name: Generate Mime Types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run update
        run: composer run-script generate-types

      - name: Run test suite
        run: composer run-script test

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v8
